# ZMK Configuration Options for SHW48+48 
# Activa ZMK Studio
CONFIG_ZMK_STUDIO=y
# Permite guardar cambios de keymap en la 
# memoria Flash no volátil
CONFIG_ZMK_STUDIO_LOCKING=n
# Habilita perfiles Bluetooth y seguridad 
# para conectar con la App Web/Desktop
CONFIG_ZMK_BLE=y
